# Site settings
title: JerryScript Engine
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  JerryScript is a very lightweight JavaScript engine with capability to run on microcontrollers with less then 8KB of RAM.
baseurl: "/jerryscript" # the subpath of your site, e.g. /blog/
url: "http://samsung.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  samsung

# Build settings
highlighter: pygments

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: pygments

#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
