version: "{build}"
branches:
  except:
  - coverity_scan
  - gh_pages
skip_tags: true

# Build matrix setup.
image:
  - Visual Studio 2017
configuration:
  - Debug
  - Release
platform:
  - x64
  - Win32

environment:
  matrix:
    - JERRY_DEBUGGER: ON
    - JERRY_DEBUGGER: OFF

# Steps of a job.
init:
  - cmake -version
before_build:
  - if "%PLATFORM%"=="Win32" cmake -G"Visual Studio 15 2017" -Bbuild -H. -DJERRY_DEBUGGER=%JERRY_DEBUGGER%
  - if "%PLATFORM%"=="x64" cmake -G"Visual Studio 15 2017 Win64" -Bbuild -H. -DJERRY_DEBUGGER=%JERRY_DEBUGGER%
build:
  project: build\Jerry.sln
  parallel: true
  verbosity: minimal
